import html

from fastapi import Request
from fastapi.responses import HTMLResponse

from dashboard import _authorized, _duration, _pct_from_entry, _pct_text, _price, _trade_label, _tv_url
from db import fetch_signal_by_id


def _pine_number(value):
    try:
        return format(float(value), ".12g")
    except (TypeError, ValueError):
        return "na"


def _pine_string(value):
    return str(value or "").replace("\\", "\\\\").replace('"', '\\"')


def pine_source(row):
    label = _trade_label(row)
    direction = str(row.get("direction") or "")
    symbol = str(row.get("symbol") or "")
    duration = _duration(row)
    entry = _pine_number(row.get("entry_price"))
    stop = _pine_number(row.get("stop_loss"))
    t1 = _pine_number(row.get("target_1"))
    t2 = _pine_number(row.get("target_2"))
    stop_pct = _pct_text(_pct_from_entry(row, "stop_loss"))
    t1_pct = _pct_text(_pct_from_entry(row, "target_1"))
    t2_pct = _pct_text(_pct_from_entry(row, "target_2"))
    evidence = float(row.get("evidence_score") or 0)
    rr = float(row.get("risk_reward") or 0)

    return f'''//@version=6
indicator("Crypto Signal Overlay — {_pine_string(symbol)}", overlay=true, max_lines_count=20, max_labels_count=20, max_boxes_count=10)

// Generated by the Crypto Signal Engine for one exact signal snapshot.
// It is visualization-only. It does not create or authorize trades.

signalLabel = "{_pine_string(label)}"
direction = "{_pine_string(direction)}"
duration = "{_pine_string(duration)}"
entry = {entry}
stop = {stop}
target1 = {t1}
target2 = {t2}
stopPct = "{_pine_string(stop_pct)}"
t1Pct = "{_pine_string(t1_pct)}"
t2Pct = "{_pine_string(t2_pct)}"
evidence = {evidence:.2f}
riskReward = {rr:.4f}

valid = not na(entry) and not na(stop) and not na(target1) and not na(target2)
isBuy = signalLabel == "BUY"
isSell = signalLabel == "SELL"
signalColor = isBuy ? color.lime : isSell ? color.red : color.orange

var line entryLine = na
var line stopLine = na
var line t1Line = na
var line t2Line = na
var box riskBox = na
var box rewardBox = na
var label infoLabel = na

if barstate.islast and valid
    if not na(entryLine)
        line.delete(entryLine)
    if not na(stopLine)
        line.delete(stopLine)
    if not na(t1Line)
        line.delete(t1Line)
    if not na(t2Line)
        line.delete(t2Line)
    if not na(riskBox)
        box.delete(riskBox)
    if not na(rewardBox)
        box.delete(rewardBox)
    if not na(infoLabel)
        label.delete(infoLabel)

    left = math.max(0, bar_index - 20)
    right = bar_index + 30
    entryLine := line.new(left, entry, right, entry, xloc=xloc.bar_index, extend=extend.right, color=color.white, width=2)
    stopLine := line.new(left, stop, right, stop, xloc=xloc.bar_index, extend=extend.right, color=color.red, width=2, style=line.style_dashed)
    t1Line := line.new(left, target1, right, target1, xloc=xloc.bar_index, extend=extend.right, color=color.lime, width=2, style=line.style_dashed)
    t2Line := line.new(left, target2, right, target2, xloc=xloc.bar_index, extend=extend.right, color=color.aqua, width=2, style=line.style_dashed)

    riskTop = math.max(entry, stop)
    riskBottom = math.min(entry, stop)
    rewardTop = math.max(entry, target2)
    rewardBottom = math.min(entry, target2)
    riskBox := box.new(left, riskTop, right, riskBottom, xloc=xloc.bar_index, bgcolor=color.new(color.red, 88), border_color=color.new(color.red, 55))
    rewardBox := box.new(left, rewardTop, right, rewardBottom, xloc=xloc.bar_index, bgcolor=color.new(color.lime, 92), border_color=color.new(color.lime, 70))

    info = signalLabel + " " + direction + "  |  " + duration + "\n" +
      "ENTRY " + str.tostring(entry, format.mintick) + "\n" +
      "STOP " + str.tostring(stop, format.mintick) + " (" + stopPct + ")\n" +
      "T1 " + str.tostring(target1, format.mintick) + " (" + t1Pct + ")\n" +
      "T2 " + str.tostring(target2, format.mintick) + " (" + t2Pct + ")\n" +
      "R:R " + str.tostring(riskReward, "#.##") + "  Evidence " + str.tostring(evidence, "#.0")
    infoLabel := label.new(bar_index, entry, info, xloc=xloc.bar_index, style=isSell ? label.style_label_down : label.style_label_up, color=signalColor, textcolor=color.black, size=size.small)

plotshape(barstate.islast and isBuy, title="BUY", style=shape.triangleup, location=location.belowbar, color=color.lime, size=size.large, text="BUY")
plotshape(barstate.islast and isSell, title="SELL", style=shape.triangledown, location=location.abovebar, color=color.red, size=size.large, text="SELL")
'''


def pine_overlay_page(request: Request, signal_id: int):
    if not _authorized(request):
        from fastapi.responses import RedirectResponse
        return RedirectResponse("/dashboard/login", status_code=303)
    row = fetch_signal_by_id(signal_id)
    if not row:
        return HTMLResponse("Signal not found", status_code=404)
    source = pine_source(row)
    symbol = html.escape(str(row.get("symbol") or ""))
    tv = html.escape(_tv_url(row))
    escaped_source = html.escape(source)
    return HTMLResponse(f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{symbol} TradingView overlay</title><style>
body{{margin:0;background:#081018;color:#edf2f7;font-family:Arial,sans-serif}}.wrap{{max-width:1100px;margin:auto;padding:22px}}.panel{{background:#111c27;border:1px solid #26394c;border-radius:14px;padding:18px}}textarea{{width:100%;height:520px;box-sizing:border-box;background:#071018;color:#d9e7f2;border:1px solid #32465a;border-radius:9px;padding:12px;font:12px Consolas,monospace}}a{{display:inline-block;text-decoration:none;font-weight:800;border-radius:8px;padding:11px 14px;margin:8px 8px 8px 0}}.tv{{background:#2962ff;color:white}}.back{{background:#26394c;color:white}}.note{{color:#aebdca;line-height:1.45}}code{{color:#dce8f3}}
</style></head><body><div class="wrap"><div class="panel"><h2>{symbol} — TradingView signal overlay</h2><p class="note">This generates the exact Pine overlay for this signal: BUY/SELL marker, entry, stop-loss area, T1/T2, expected move percentages, duration, R:R and evidence. TradingView does not let an external website inject arbitrary Pine/drawings into a chart URL, so the safe supported path is: open TradingView, paste this generated script into Pine Editor, then click <b>Add to chart</b>.</p><a class="tv" target="_blank" rel="noopener" href="{tv}">1. OPEN TRADINGVIEW ↗</a><a class="back" href="/dashboard/signal/{signal_id}">Back to signal</a><p class="note"><b>2.</b> Copy the script below into TradingView → Pine Editor → <b>Add to chart</b>.</p><textarea readonly>{escaped_source}</textarea></div></div></body></html>''')
