alter table public.paper_trades
    add column if not exists signal_generated_at timestamptz,
    add column if not exists decision_at timestamptz,
    add column if not exists entry_observed_market_price numeric,
    add column if not exists entry_fill_observed_at timestamptz,
    add column if not exists entry_supported_notional numeric,
    add column if not exists entry_slippage_bps numeric,
    add column if not exists entry_source_count integer,
    add column if not exists execution_model_version text not null default 'legacy_v1',
    add column if not exists exit_trigger_observed_price numeric,
    add column if not exists exit_fill_observed_at timestamptz,
    add column if not exists exit_supported_notional numeric,
    add column if not exists exit_slippage_bps numeric,
    add column if not exists exit_source_count integer;

create table if not exists public.paper_signal_decisions (
    id bigint generated by default as identity primary key,
    account_id text not null,
    signal_key text not null unique,
    scan_id text,
    symbol text not null,
    horizon text not null,
    direction text not null,
    action text,
    evidence_score numeric,
    decision text not null,
    reason text not null,
    signal_generated_at timestamptz,
    decided_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists paper_signal_decisions_account_time_idx
    on public.paper_signal_decisions(account_id, decided_at desc);

create table if not exists public.paper_reconciliation_snapshots (
    id bigint generated by default as identity primary key,
    account_id text not null,
    verified boolean not null,
    status text not null,
    expected_cash numeric,
    expected_equity numeric,
    expected_realized_pnl numeric,
    open_pnl numeric,
    open_notional numeric,
    cash_delta numeric,
    equity_delta numeric,
    realized_delta numeric,
    trade_mismatch_ids bigint[] not null default '{}',
    reasons text[] not null default '{}',
    created_at timestamptz not null default now()
);

create index if not exists paper_reconciliation_account_time_idx
    on public.paper_reconciliation_snapshots(account_id, created_at desc);

create or replace function public.enforce_paper_trade_append_only()
returns trigger
language plpgsql
as $$
begin
    if tg_op = 'DELETE' then
        raise exception 'paper_trades are append-only and cannot be deleted';
    end if;

    if old.status = 'CLOSED' then
        raise exception 'closed paper_trades are immutable';
    end if;

    if new.account_id is distinct from old.account_id
       or new.signal_key is distinct from old.signal_key
       or new.scan_id is distinct from old.scan_id
       or new.symbol is distinct from old.symbol
       or new.horizon is distinct from old.horizon
       or new.direction is distinct from old.direction
       or new.entry_price is distinct from old.entry_price
       or new.stop_loss is distinct from old.stop_loss
       or new.target_price is distinct from old.target_price
       or new.quantity is distinct from old.quantity
       or new.notional_usd is distinct from old.notional_usd
       or new.risk_usd is distinct from old.risk_usd
       or new.fee_bps_one_way is distinct from old.fee_bps_one_way
       or new.evidence_score is distinct from old.evidence_score
       or new.research_only is distinct from old.research_only
       or new.opened_at is distinct from old.opened_at
       or new.created_at is distinct from old.created_at
       or new.signal_generated_at is distinct from old.signal_generated_at
       or new.decision_at is distinct from old.decision_at
       or new.entry_observed_market_price is distinct from old.entry_observed_market_price
       or new.entry_fill_observed_at is distinct from old.entry_fill_observed_at
       or new.entry_supported_notional is distinct from old.entry_supported_notional
       or new.entry_slippage_bps is distinct from old.entry_slippage_bps
       or new.entry_source_count is distinct from old.entry_source_count
       or new.execution_model_version is distinct from old.execution_model_version
    then
        raise exception 'paper trade entry identity/evidence is immutable';
    end if;

    if new.status <> 'CLOSED' then
        raise exception 'paper trade status may only transition OPEN to CLOSED';
    end if;
    if new.closed_at is null or new.exit_price is null or new.exit_reason is null or new.pnl_usd is null or new.pnl_pct is null then
        raise exception 'paper trade closure evidence is incomplete';
    end if;
    return new;
end;
$$;

drop trigger if exists paper_trades_append_only_guard on public.paper_trades;
create trigger paper_trades_append_only_guard
before update or delete on public.paper_trades
for each row execute function public.enforce_paper_trade_append_only();

grant select, insert on table public.paper_signal_decisions to service_role;
grant select, insert on table public.paper_reconciliation_snapshots to service_role;
grant usage, select on sequence public.paper_signal_decisions_id_seq to service_role;
grant usage, select on sequence public.paper_reconciliation_snapshots_id_seq to service_role;
